### ISSUE TITLE
Game crashes when loading title screen

### ISSUE THREAD

**Issue by StereoMadnessss** [MicherGit/Zetamod#7]
When loading the title screen the game crashes instantly. The version is 1.1.0_01 and I am on a mac.

**Comment by MicherGit** [comment]
Oh hello there. Try the lastest 2.0 build or 1.2, I removed title screen mixins due to issues running with some hardware in 1.2.0, 1.2.1 is in development rn and will release soon. I will probably release a patch for 1.1.x releases / java 8 that fixes this.

**Comment by StereoMadnessss** [comment]
apparently it's a mixin thing so I guess I'll close it
